### ISSUE TITLE
Clarity needed over Connecting AVS using a separate transit VNET section

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/AzureCAT-AVS#1]
thanks for a very detailed scenario guide :-)

i am trying to understand more about the scenario covered in [Connecting AVS using a separate transit VNET](https://github.com/Azure/AzureCAT-AVS/tree/main/networking/deploy-nva-with-vxlan-in-transit-vnet-and-route-server#connecting-avs-using-a-separate-transit-vnet).

it is mentioned that *...As only one VNET Gateway can be part of one VNET a separate VNET is required as well...*.  statement itself is correct. but why AVS D-MSEE circuit can't be terminated on same VNet ER gateway which is used to terminate on-premise ER circuit?

as documented [here](https://docs.microsoft.com/en-us/azure/expressroute/expressroute-faqs#can-i-have-multiple-expressroute-circuits-in-the-same-metro-can-i-link-them-to-the-same-virtual-network), an ER gateway can be used to terminate upto 4 ER circuits.

 look forward to response.

thanks!

**Comment by msftphleiten** [comment]
you can terminate it on the same ExR Gateway, but there is no transit and you can't send the traffic through an NVA.
if don't need firewalling you can connect them to the same ExR and use GlobalReach.
